version: '3.9'
services:
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  kafka:
    image: docker.redpanda.com/vectorized/redpanda:v24.1.2
    command: [
      "redpanda", "start",
      "--overprovisioned", "--smp", "1", "--memory", "512M",
      "--reserve-memory", "0M", "--node-id", "0",
      "--check=false"
    ]
    ports:
      - "9092:9092"
    environment:
      - REDPANDA_AUTO_CREATE_TOPICS=true
  minio:
    image: minio/minio:RELEASE.2024-07-26T20-48-21Z
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
      - "9000:9000"
      - "9001:9001"

