apiVersion: batch/v1
kind: CronJob
metadata:
  name: boilerplate-retention
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: retention
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command: ["node", "dist/jobs/dataRetention.js"]
          restartPolicy: OnFailure

